defaultIndent: '  '
removeTrailingWhitespace: 1
indentPreamble: 1
modifyLineBreaks:
  textWrap:
    columns: 80
  oneSentencePerLine:
    manipulateSentences: 1
lookForAlignDelims:
  tabular:
    delimiter: '&'
    alignDoubleBackSlash: 1
